version: '3.9'
services:
  sv_web:
    container_name: web
    build:
      context: ./
      dockerfile: dockerfile-php
    depends_on:
      - sv_db
    restart: always
    volumes:
           - ./www/:/var/www/html/
    ports:
        - '8080:80'
    networks:
       vpcbr:
         ipv4_address: 10.1.1.11

  sv_db:
    image: mysql:5.6
    volumes:
    - ./mysql-backup/:/docker-entrypoint-initdb.d/
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: register_db
      MYSQL_USER: yhospat
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - '3306:3306'
    networks:
       vpcbr:
         ipv4_address: 10.1.1.22

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1
